      - name: Reproduce original command
        env:
          TITLE: ${{ inputs.title }}

        run: |
          echo "===== BEFORE ====="

          curl --version

          curl \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"title": ${{ toJson(env.TITLE) }}}' \
            http://127.0.0.1:9

          echo "===== AFTER ====="
